CREATE TABLE IF NOT EXISTS names (
	name TEXT PRIMARY KEY,
	key TEXT NOT NULL,
	sig TEXT
);

CREATE TABLE IF NOT EXISTS revocations (
	fp TEXT PRIMARY KEY,
	reason TEXT NOT NULL DEFAULT '',
	sig TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS claim_rate (
	ip TEXT NOT NULL,
	day INTEGER NOT NULL,
	count INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (ip, day)
);
